/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern edge * createedge ( graph * g, node * from, node * to );
extern edge * addedge ( graph * g, edge * e );
extern edgelist * createedgelist ( graph * g );
extern int sizeofedge ( void );

#else /* __STDC__ */

extern edge * createedge ( graph * g, node * from, node * to );
extern edge * addedge ( graph * g, edge * e );
extern edgelist * createedgelist ( graph * g );
extern int sizeofedge ( void );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
