/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern graph * creategraph ( graph * rootgraph );
extern int sizeofgraph ( void );

#else /* __STDC__ */

extern graph * creategraph ( graph * rootgraph );
extern int sizeofgraph ( void );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
