/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern void tlayout ( graph * g, int cornerx, int cornery, int distx, int disty, int vertical, int crossingiterations, int placementiterations );
extern void privateonuppernb ( graph * g, node * n1, node * n2 );
extern void privateonlowernb ( graph * g, node * n1, node * n2 );
extern void onnbsdo ( graph * g, node * n, node_fun onuppernb, node_fun onlowernb );
extern void privatebuildandinitializematrices ( graph * g );
extern void privateupdatenodepositions ( void );
extern int privatelowestnodepositions ( void );
extern void tnewnodecoordinates ( int vert, int min_pos );
extern void recalculateedgeendpointsofselectednodes ( graph * g );

#else /* __STDC__ */

extern void tlayout ( graph * g, int cornerx, int cornery, int distx, int disty, int vertical, int crossingiterations, int placementiterations );
extern void privateonuppernb ( graph * g, node * n1, node * n2 );
extern void privateonlowernb ( graph * g, node * n1, node * n2 );
extern void onnbsdo ( graph * g, node * n, node_fun onuppernb, node_fun onlowernb );
extern void privatebuildandinitializematrices ( graph * g );
extern void privateupdatenodepositions ( void );
extern int privatelowestnodepositions ( void );
extern void tnewnodecoordinates ( int vert, int min_pos );
extern void recalculateedgeendpointsofselectednodes ( graph * g );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
