/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern int ginger_init ( void *(*mallocroutine) (size_t n), void (*freeroutine) (void *p), int argc, char **argv );
extern int ginger_deinit ( void );
extern int ginger_check ( FILE * stream );
extern graph * ginger_graph ( graph * rootedgraph );
extern node * ginger_node ( graph * g, char *name );
extern edge * ginger_edge ( graph * g, char *src, char *dst );
extern int ginger_machine ( FILE * stream );
extern int ginger_log ( FILE * stream, int level );
extern int ginger_randinit ( void );
extern int ginger_rand ( void );

#else /* __STDC__ */

extern int ginger_init ( void *(*mallocroutine) (size_t n), void (*freeroutine) (void *p), int argc, char **argv );
extern int ginger_deinit ( void );
extern int ginger_check ( FILE * stream );
extern graph * ginger_graph ( graph * rootedgraph );
extern node * ginger_node ( graph * g, char *name );
extern edge * ginger_edge ( graph * g, char *src, char *dst );
extern int ginger_machine ( FILE * stream );
extern int ginger_log ( FILE * stream, int level );
extern int ginger_randinit ( void );
extern int ginger_rand ( void );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
