/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern int log_s ( char *func );
extern int log_e ( char *func );
extern int log_m ( const char *format, ... );
extern void log_matrixarray ( matrix * *mm, int n );
extern void log_matrix ( matrix * m );
extern void log_nodelist ( graph * g );
extern void log_edgelist ( graph * g );

#else /* __STDC__ */

extern int log_s ( char *func );
extern int log_e ( char *func );
extern int log_m ( const char *format, ... );
extern void log_matrixarray ( matrix * *mm, int n );
extern void log_matrix ( matrix * m );
extern void log_nodelist ( graph * g );
extern void log_edgelist ( graph * g );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
