/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern int machine_init ( int argc, char **argv );
extern int machine_deinit ( void );
extern int machine_check ( FILE * stream );
extern size_t machine_memchunk ( void );
extern int machine_endian ( void );
extern int machine_intbits ( void );
extern int machine_longsize ( void );
extern int machine_shortsize ( void );

#else /* __STDC__ */

extern int machine_init ( int argc, char **argv );
extern int machine_deinit ( void );
extern int machine_check ( FILE * stream );
extern size_t machine_memchunk ( void );
extern int machine_endian ( void );
extern int machine_intbits ( void );
extern int machine_longsize ( void );
extern int machine_shortsize ( void );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
