/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern int pool_init ( void );
extern int pool_deinit ( void );
extern pool pool_create ( void );
extern void * pool_malloc ( pool p, size_t n );
extern pool pool_delete ( pool pp );
extern int pool_check ( FILE * stream );

#else /* __STDC__ */

extern int pool_init ( void );
extern int pool_deinit ( void );
extern pool pool_create ( void );
extern void * pool_malloc ( pool p, size_t n );
extern pool pool_delete ( pool pp );
extern int pool_check ( FILE * stream );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
