/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern int mm_init ( void );
extern int mm_deinit ( void );
extern void mmfree ( void *p );
extern void * mmalloc ( size_t n );
extern int mm_check ( FILE * stream );

#else /* __STDC__ */

extern int mm_init ( void );
extern int mm_deinit ( void );
extern void mmfree ( void *p );
extern void * mmalloc ( size_t n );
extern int mm_check ( FILE * stream );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
