/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern node * createnode ( graph * g, char *name );
extern node * addnode ( graph * g, node * n );
extern node * findnode ( graph * g, char *name );
extern void cnodeselectioncount ( void *b );
extern int nodeselectcount ( graph * g );
extern node * startnode ( graph * g );
extern nodelist * createnodelist ( graph * g );
extern node * startnodelist ( graph * g );
extern node * nextnodelist ( graph * g, nodelist * n );
extern int sizeofnode ( void );

#else /* __STDC__ */

extern node * createnode ( graph * g, char *name );
extern node * addnode ( graph * g, node * n );
extern node * findnode ( graph * g, char *name );
extern void cnodeselectioncount ( void *b );
extern int nodeselectcount ( graph * g );
extern node * startnode ( graph * g );
extern nodelist * createnodelist ( graph * g );
extern node * startnodelist ( graph * g );
extern node * nextnodelist ( graph * g, nodelist * n );
extern int sizeofnode ( void );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
