/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern void postscriptgraph ( graph * g, FILE * fd );
extern void postscriptedge ( edge * e, FILE * fd );
extern void postscriptinitialize ( FILE * fd );
extern void postscriptend ( FILE * fd );
extern void postscriptnode ( node * n, FILE * fd );
extern void psnode ( void *n );
extern void psedge ( void *e );
extern void psedgecalcendpointsps ( void *e );
extern void psedgecalcendpoints ( void *e );
extern void psnodeboundingrectangle ( void *n1 );
extern void postscriptdetermineboundingrectangle ( graph * g );
extern void postscriptellipse ( int x, int y, int w, int h, FILE * fd );
extern void postscriptrhomb ( int x, int y, int w, int h, FILE * fd );
extern void postscriptrectangle ( int x1, int y1, int x2, int y2, FILE * fd );
extern void postscripttext ( char *text, FILE * fd );
extern void postscriptarrow ( int x1, int y1, int x2, int y2, int dir, FILE * fd );

#else /* __STDC__ */

extern void postscriptgraph ( graph * g, FILE * fd );
extern void postscriptedge ( edge * e, FILE * fd );
extern void postscriptinitialize ( FILE * fd );
extern void postscriptend ( FILE * fd );
extern void postscriptnode ( node * n, FILE * fd );
extern void psnode ( void *n );
extern void psedge ( void *e );
extern void psedgecalcendpointsps ( void *e );
extern void psedgecalcendpoints ( void *e );
extern void psnodeboundingrectangle ( void *n1 );
extern void postscriptdetermineboundingrectangle ( graph * g );
extern void postscriptellipse ( int x, int y, int w, int h, FILE * fd );
extern void postscriptrhomb ( int x, int y, int w, int h, FILE * fd );
extern void postscriptrectangle ( int x1, int y1, int x2, int y2, FILE * fd );
extern void postscripttext ( char *text, FILE * fd );
extern void postscriptarrow ( int x1, int y1, int x2, int y2, int dir, FILE * fd );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
