/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern int uniqstr_init ( void );
extern int uniqstr_deinit ( void );
extern char * uniqstr ( char *s );
extern int uniqstr_check ( FILE * stream );

#else /* __STDC__ */

extern int uniqstr_init ( void );
extern int uniqstr_deinit ( void );
extern char * uniqstr ( char *s );
extern int uniqstr_check ( FILE * stream );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
