/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern int vparse ( char *filename, graph * g );

#else /* __STDC__ */

extern int vparse ( char *filename, graph * g );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
